### ISSUE TITLE
Freezing dock2

### ISSUE THREAD

**Issue by Ng76i4** [callmeEthan/Dock2#1]
Bug
![bug2](https://user-images.githubusercontent.com/76935541/166814085-58e89891-5fbb-49da-95bc-bb5c3742795a.gif)
![bug](https://user-images.githubusercontent.com/76935541/166814188-1956faf5-f82f-459a-8d27-669d2828f9a3.png)
Rainmeter Log
![log](https://user-images.githubusercontent.com/76935541/166814151-1635cb2f-449b-41ae-9862-d45070e7fcee.png)
After Refresh skin
![Video_2022-05-04_130457](https://user-images.githubusercontent.com/76935541/166817693-42ccf03e-053e-4e17-b3fd-6e548b81ffd3.gif)

What happened: can not interact with skin
Reproduce: 1 out of 5 it happens when going back to the desktop after using rainmeter game mode (unload all skin in full screen)
Rainmeter version: 4.5.13.3632 (64-bit)

**Comment by callmeEthan** [comment]
Problem i had too, althought it rarely happens and hard to replicate, probably error on rainmeter side, I usually just restart skin/rainmeter and ignore it

**Comment by Ng76i4** [comment]
It happens pretty often with me. Maybe because I used the rainmeter game mode, which loads and unloaded skins more frequently
