### ISSUE TITLE
Can you use the Dock 2 skin animation to help me make a mini info pop-up skin?

### ISSUE THREAD

**Issue by Purehowaito** [callmeEthan/Dock2#2]
Hello not-Finch author. I liked the animation effect of your Dock 2 skin very much, so I wanted to try to make a message pop-up skin with smooth animation, I don't know much about code, rainmeter only used for half a year, so I wanted to try to make changes based on your work but finally failed, it was just a rough look.

I really don't know what to do, it seems like I have to modify lua, but I don't know much about lua, so can you help me make a simple example or deal with lua or other code?

I posted this question to https://forum.rainmeter.net/viewtopic.php?p=207681#p207681 if you're interested.

Or is it possible to pay you $25 with PayPal and seek your technical help to make the skin I need?

**Comment by callmeEthan** [comment]
So maybe I could help you, but I'm not sure what exactly you're trying to
achieve. Can you provide a more detailed description or some visual
presentation of what you trying to make?

**Comment by Purehowaito** [comment]
Thanks to the author for taking the time to help me with this code novice!! I'm not sure if what I want is unrealistic, so please let me know if yes. Here are my needs.

The text of the album and year is rendered automatically after the skin is activated when iTunes switches to the next song (or a song is played). (That's the main thing)

1. The text and rectangle's entry and exit animations are consistent, like the GIF below. It would be better if you could set a time delay to pop up.
![1](https://user-images.githubusercontent.com/67429688/171983977-26713d66-3e48-436e-bd55-11ebc431a5cb.gif)

2. The border of the rectangle always automatically adapts to the length of the text, because the length of the text is not always fixed, I want to show all the text. The text in the following image is hand-aligned by me. (Much like a subtitle whose background is rounded rectangle)
![2](https://user-images.githubusercontent.com/67429688/171984123-8b83b07c-2e9d-40b4-a644-c1cc2d4229a8.png)
![5](https://user-images.githubusercontent.com/67429688/171984133-cb953b3a-961a-4d20-8587-debef164bff8.png)
![4](https://user-images.githubusercontent.com/67429688/171984138-c77d8666-771a-4b3f-9d2f-269e35d0c62a.png)
![3](https://user-images.githubusercontent.com/67429688/171984141-5434d99a-e88e-4ed1-8bc2-f7631eef4d9a.png)

3. It would be nice to be able to add FrostedGlass to a rectangle, but I found on the skin of other authors that FrostedGlas doesn't fit a rounded rectangle, it gets weird, that's roughly what it looks like, if you can do that thank you. (Minor)
![1](https://user-images.githubusercontent.com/67429688/171984184-0d894243-f642-4ca0-b961-a9fd9ede6a80.png)

Summary: All I need is a very concise skin with no other additional features, all of its code is prepared to automatically pop up a small window of text with gorgeous animations.

**Comment by callmeEthan** [comment]
Oh I had thought It'd be something complicated since you ripping code from
dock 2, but yes, a simple text pop-up is possible. How is your code right
now?

**Comment by Purehowaito** [comment]
It's still the same, I don't know how to go on, it's too difficult for me

**Comment by callmeEthan** [comment]
Lua code isn't necessary, you can achieve this with shape meter,
calculation and action timer measure.
Lua code is for complicated task (like auto generate/dynamic stuff),

**Comment by Purehowaito** [comment]
Oh, I see! However, with my current ability, I will only use AudioLevel, NowPlaying, Chameleon and other plug-ins and make simple text and time. I was very surprised when I first saw your Dock 2 work! I didn't expect Rainmeter to achieve an animation comparable to iOS, completely refreshing my understanding. However, I am very unfamiliar with ActionTimer. It seems that I still have a long way to go. If you finish the finished product, I will study it carefully and may make something else. Thank you!!

If you have finished making it, please email me: Pyuahowaito@hotmail.com. Send the installation package and Paypal link. I will pay you $25 as a thank you. This is my first gift for my overseas friend. Please let me have a try.

**Comment by callmeEthan** [comment]
I have made a basic [example](https://github.com/callmeEthan/Popuptext/releases/download/ex/Popup.text_0.1.rmskin)
It only use calc and action timer measure, not lua script needed
btw my paypal is annesapphire4@gmail.com

**Comment by Purehowaito** [comment]
Please check, I added another $5, almost the way I wanted it, I liked it very much, thank you!! But I have one last question: is there any way to play iTunes songs and automatically switch to the next one to automatically start the skin? Automate this. Then add a 1-5 second time delay function before it starts automatically, I want it to start automatically (the following video is what I manually simulate the automation looks like)

https://user-images.githubusercontent.com/67429688/172068642-a111b7fc-199a-4b2d-8604-64ae77ae2dc8.mp4

If you write these in lua, will it be smoother and more performance-saving? (Just asking doesn't need to do that)

**Comment by callmeEthan** [comment]
You can create a [NowPlaying](https://docs.rainmeter.net/manual/measures/nowplaying/) measure skin (It should works with iTune, not that I use iTune so I can't test that out). And when it change track, use WriteKeyValue bang to write info into pop-up skin, then use ActivateConfig to open pop-up skin ([manual](https://docs.rainmeter.net/manual/bangs/)).  

This is simplest way, disadvantage is that if tracks changes quickly it will mess things up.
I also made an [Example](https://github.com/callmeEthan/Popuptext/releases/download/ex_2/Popup.text_0.2.rmskin)

Also, I don't think written in lua will have any significant performance-saving effect, it's for more complicated task that require many intricate functions.
edit: grammar

**Comment by Purehowaito** [comment]
Thank you very much for the stable work! 

[! ActivateConfig "#ROOTCONFIG#" "Popup.ini"] 
This line of code when I put the .ini to modify the Japanese and Kanji, the automation does not work, is there a solution?

**Comment by callmeEthan** [comment]
You can check [Rainmeter log](https://docs.rainmeter.net/manual/user-interface/about/) too see what error rainmeter is having.
I don't know about japanese but there shouldn't be space in bang command, it's "**!ActivateConfig**", not "! ActivateConfig".  
like: [!ActivateConfig "#ROOTCONFIG#" "Popup.ini"]

**Comment by Purehowaito** [comment]
Thanks for pointing!

**Comment by Purehowaito** [comment]
Sorry to bother you. I found a problem when I used it. When it showed too much text, it would go beyond the screen.
![1](https://user-images.githubusercontent.com/67429688/172270650-fb1ef5c3-c6fb-4567-be6b-542e49edb379.png)

Is there any way to set an upper limit and replace the excess part with "..."? Can you just omit Album instead of Year? Just like below.
![2](https://user-images.githubusercontent.com/67429688/172270671-d641d2af-74c5-499e-8fd1-d4c88b6cbba8.png)

When I added ClipString=1 and W=1500 to it, it always kept the length of 1500.
![3](https://user-images.githubusercontent.com/67429688/172270693-3c754c82-1bd3-468b-a14c-86f649765c78.png)

**Comment by callmeEthan** [comment]
If string meter don't have size value `W`,`H` defined, the size change according to text length, then I use `!SetVariable WTransition ([MeterText:W]+#Size#/2)` to adjust the background to fit the text.
Since you overwrite text width value `W=1500`, background would only uses that value.
Instead you can avoid using W, use `ClipString=2` and `ClipStringW=1000`. Also define `H=#Size#` so it won't break line.
[String meter document](https://docs.rainmeter.net/manual/meters/string/)

**Comment by Purehowaito** [comment]
Can you modify it in example 0.2? Sorry, I still don't know how to modify the code... This is the text I need to adjust.

[MeterText]
Meter=STRING
MeasureName=MeasureAlbum
MeasureName2=MeasureYear
X=(#Size#/5)
Y=(#Size#/2)
FontColor=#FontColor#,[ACurrent]
FontSize=25
FontFace=Montserrat
DynamicVariables=1
StringAlign=LeftCenter
Text=%1 - %2
Container=MeterContainer
AntiAlias=1

[MeasureAlbum]
Measure=NowPlaying
PlayerName=iTunes
PlayerType=ALBUM
UpdateDivider=1

[MeasureYear]
Measure=NowPlaying
PlayerName=iTunes
PlayerType=YEAR
UpdateDivider=1

**Comment by callmeEthan** [comment]
Can you send the file, it seem you have a different approach than I

**Comment by Purehowaito** [comment]
[Popup-text.zip](https://github.com/callmeEthan/Dock2/files/8850649/Popup-text.zip)

**Comment by callmeEthan** [comment]
I updated the [example](https://github.com/callmeEthan/Popuptext/releases/download/ex_3/Popup.text_0.21.rmskin) (works with Spotify)
Removed !WriteKeyValue from measure.ini since you already put separate measures in pop-up skin itself.
Set measures Updatedivider=-1 in pop-up skin because they only need to update once to get track info.

**Comment by Purehowaito** [comment]
I want to put the year at the end, but it always omits the text of the latter. Can it be achieved if it is separated like the following sample code?

[mYear]
Measure=String
String=year

[mTitle]
Measure=String
String=title

[tYear]
Meter=String
MeasureName=mYear
StringAlign=Right
X=250
Y=r
W=150
H=50
AntiAlias=1
FontFace=Montserrat
FontSize=20
FontColor=255,255,255,255
DynamicVariables=1
SolidColor=100,100,100,255
TrailingSpaces=1
text="  %1  "

[tTitle]
Meter=String
MeasureName=mTitle
StringAlign=Left
X=0
Y=r
W=100
H=50
AntiAlias=1
FontFace=Montserrat
FontSize=20
FontColor=100,100,100,255
DynamicVariables=1
SolidColor=255,255,255,255
TrailingSpaces=1
text="  %1  "

**Comment by callmeEthan** [comment]
Yes, it can be achieve with 2 text meter, but you need to change shape's calculation to account for the size of both text meter.
Another [example](https://github.com/callmeEthan/Popuptext/releases/download/ex_3/Pop.up.text_0.22.rmskin)

**Comment by Purehowaito** [comment]
Yes, I don't know how to modify it. All my problems have been solved. Thank you very much for your patient advice and examples! Have a good day!!!
