### ISSUE TITLE
Issue with drag and drop and removing background

### ISSUE THREAD

**Issue by adrian5683** [callmeEthan/Dock2#3]
Hi, just started using this dock and it looks and works great. I had to manually add all the images for every icon since drag and drop doesn't seem to work for me. I select toggle edit and then try dragging and dropping any .png or .jpg file with no success, it just shows the crossed out circle indicator. Any ideas why?

Also, when I delete the background line from Global Settings to remove the dock background, some sub-docks have invisible backgrounds and some don't, like Power. Is the behavior supposed to be consistent across all sub-docks as well? Or is there a way to manually control it through one of the variables? I'd love to have the sub-docks open with visible backgrounds and only the main dock be invisible.

Anyway, love the dock and thank you for your work. I'm using the latest versions of Windows 10 and Rainmeter.

**Comment by callmeEthan** [comment]
I have encountered issue with drag and drop before, it's either DragNDrop plugin is missing in rainmeter, or rainmeter is running as administrator and explorer doesn't allow drag and drop onto windows with elevated privilege.

And yes, "Global.settings" will apply consistency across across all dock and sub-docks, however "Settings" isn't, you can apply setting for sub-dock individually, just right click them > choose Setting and add your own line of "background", Power dock have it's own background value so it override global.settings.

**Comment by adrian5683** [comment]
Thank you, the plugin was indeed missing from Rainmeter, and Global vs Settings works as intended as well. Thanks again.
