### ISSUE TITLE
Multiple Docks cause background to remain on second dock

### ISSUE THREAD

**Issue by eXcalpius** [callmeEthan/Dock2#4]
Amazing skin! It has so much utility that I've set up two docks, each with their own skin folder (re: Another Dock and Another Dock 2). The second dock will not allow the dock background to disappear completely (like the first one does) when the Background line is commented out with ; in the GlobalSettings.inc. If the background is not commented out, it does obey the background color parameter, if that helps.

Obviously, this is not a critical issue. If there's a simple way I can make the background of Dock 2 disappear like it does for Dock 1, I'd greatly appreciate a heads up. Thanks for all of your hard work.

**Comment by callmeEthan** [comment]
Apology for the late respond, rarely check github and it doesn't have notification.
I tried to replicate this but there is no issues, but I did made a few update since so it's probably fixed(?)
You could try the newer version, I just added hotkey so it's even more convenient.

**Comment by eXcalpius** [comment]
No problem. Fortunately, I was able to use the old version for my one dock and the new version to replace the second dock, and now both have fully transparent backgrounds as desired. So, you did help! Thanks. :)
